version: '3.1'

services:

  ### Application ###
  app:
    image: saga-order-service
    build: ../
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb

  ### ordersdb ###
  postgresqldb:
    image: postgres
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres