### Application configurations
server:
  port: 8085

### Datasource configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TSDB
    username: ronan
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
