server:
  port: 8081
spring:
  datasource:
    url:  jdbc:postgresql://postgresqldb:5432/orderdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create